name: Checks

on:
  push:
    branches:
      - master
      - main
      - next
  pull_request:
    branches:
      - master
      - main
      - next

jobs:
  test-node:
    name: Test on Node.js v${{ matrix.node-version }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x, 17.x, 18.x]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: install
        run: npm ci
      - name: run tests
        run: npm run test
        env:
          CI: true
  test-os:
    name: Test on ${{ matrix.os }} using Node.js LTS
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - name: install
        run: npm ci
      - name: run tests
        run: npm run test
        env:
          CI: true
  release:
    if:
      # prettier-ignore
      ${{ github.event_name == 'push' && (github.event.ref == 'refs/heads/main' || github.event.ref == 'refs/heads/next' || github.event.ref == 'refs/heads/master') }}
    name: Release new version
    needs: [test-node, test-os]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - name: install
        run: npm ci
      - run: npm run build
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
